import type { Drill } from "../types.js";

/** Footwork, finding space and beating a defender. See docs/content-sourcing.md. */
export const EVASION: Drill[] = [
  {
    id: "drill-tag-and-turn",
    title: "Tag and turn",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u7",
    maxAge: "u8",
    minutes: 8,
    players: { min: 6, max: 16 },
    space: "15 x 25 m",
    diagram: {
      space: [15, 25],
      cones: [[0, 18], [7.5, 18], [15, 18], [0, 13], [7.5, 13], [15, 13]],
      defence: [[7.5, 15.5], [8.5, 23], [11.5, 23], [14.5, 23]],
      attack: [[5, 21]],
      runs: [[[5, 18.5], [2.5, 6], 1.5]],
      ball: [[5, 18.8]],
    },
    equipment: [
      { item: "cone", qty: 6 },
      { item: "tag", qty: 2, per: "player" },
      { item: "ball", qty: 1, per: "pair" },
    ],
    setup: "Attackers on one line. One defender in a five metre channel in front of them.",
    howItRuns:
      "Run at the defender and try to get past. The defender takes one tag and holds it up. If you lose a tag you stop, hand the ball on, then collect your tag and put it back before rejoining. Rotate the defender every four goes.",
    coachingPoints: [
      "Change your angle before you get within reach, not after",
      "Defenders watch the hips, not the ball or the head",
      "Hold the tag up straight away so the referee sees it",
    ],
    progressions: ["Two defenders in the channel"],
    regressions: ["Walk it through", "Wider channel"],
    faults: [
      {
        looks: "Running straight at the defender then stepping when it is too late",
        say: "Change your angle from three steps away, not one",
      },
      {
        looks: "Defenders watching the ball, so a shoulder drop beats them",
        say: "Watch their hips. Hips cannot lie to you",
      },
    ],
  },
  {
    id: "drill-gate-choice",
    title: "Pick your gate",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u7",
    minutes: 8,
    players: { min: 6, max: 20 },
    space: "20 x 15 m",
    diagram: {
      space: [15, 20],
      cones: [
        [0, 10],
        [3, 10],
        [6, 10],
        [9, 10],
        [12, 10],
        [15, 10],
        [0, 0],
        [15, 0],
        [0, 20],
        [15, 20],
      ],
      defence: [[7.5, 9.2]],
      attack: [[7.5, 16]],
      runs: [[[7.5, 14], [4.5, 10.6]], [[4.5, 9.4], [4.5, 4]]],
      ball: [[7.5, 14.2]],
    },
    equipment: [{ item: "cone", qty: 10 }, { item: "ball", qty: 1 }],
    setup: "Three gates side by side across a channel, three metres wide each. A defender behind them.",
    howItRuns:
      "Run at the gates with the ball. The defender picks one gate to stand in. You go through a different one. Eight goes each. That is it. All you want is a child who looks up and chooses instead of running at whoever is in front of them.",
    coachingPoints: [
      "Look up before you run, then pick",
      "Commit to your gate. Changing your mind late gets you caught",
      "Ball in two hands so you are ready to do something else",
    ],
    progressions: ["Defender starts moving before you set off", "Two defenders in three gates"],
    regressions: ["Four gates", "Defender stands still until you commit"],
    faults: [
      {
        looks: "Head down, running at whichever gate is straight ahead",
        say: "Look up first. Where are they standing?",
      },
      {
        looks: "Changing gate at the last second and getting caught between two",
        say: "Pick it and commit. Wrong gate quickly beats right gate late",
      },
    ],
  },
  {
    id: "drill-side-step-slalom",
    title: "Side step slalom",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u7",
    minutes: 7,
    players: { min: 4 },
    space: "20 m channel",
    diagram: {
      space: [8, 20],
      cones: [[4, 17], [4, 15], [4, 13], [4, 11], [4, 9], [4, 7], [4, 5], [4, 3]],
      attack: [[4, 19.2]],
      runs: [
        [[4, 18.6], [2.4, 17]],
        [[2.4, 17], [5.6, 15]],
        [[5.6, 15], [2.4, 13]],
        [[2.4, 13], [5.6, 11]],
        [[5.6, 11], [2.4, 9]],
        [[2.4, 9], [5.6, 7]],
        [[5.6, 7], [2.4, 5]],
        [[2.4, 5], [5.6, 3]],
      ],
      ball: [[5.9, 19.2]],
    },
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup: "Eight cones in a line, two metres apart, up a channel.",
    howItRuns:
      "Run the line and step off the outside foot at every cone. Walk it once, jog it twice, then run it. Four goes each. It teaches the mechanics with nobody chasing them, so when somebody is chasing them the feet already know what to do.",
    coachingPoints: [
      "Push off the outside foot, do not just lean over",
      "Short choppy steps as you get near the cone",
      "Head and eyes stay up the pitch",
    ],
    progressions: ["Carry a ball", "A defender stands at the last cone"],
    regressions: ["Wider spacing", "Walk it all the way through"],
    faults: [
      {
        looks: "Leaning over at the cone with the feet carrying straight on",
        say: "Push off the outside foot. Feel it in your leg",
      },
      {
        looks: "Long strides into the cone so there is no time to change direction",
        say: "Little steps as you get close. Chop them up",
      },
    ],
  },
  {
    id: "drill-british-bulldog-ball",
    title: "Bulldog with a ball",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u7",
    minutes: 9,
    players: { min: 8, max: 24 },
    space: "25 x 20 m",
    diagram: {
      space: [25, 20],
      cones: [[0, 20], [12.5, 20], [25, 20], [0, 0], [12.5, 0], [25, 0]],
      defence: [[6.5, 18.5], [13.5, 18.5], [20.5, 18.5], [9, 10], [16, 11]],
      attack: [[3, 18.5], [10, 18.5], [17, 18.5], [24, 18.5]],
      runs: [[[6.5, 17.3], [4.5, 1.5], -2], [[20.5, 17.3], [22.5, 1.5], 2]],
      ball: [[3, 16.5], [10, 16.5], [17, 16.5], [24, 16.5]],
    },
    equipment: [{ item: "cone", qty: 6 }, { item: "tag", qty: 2, per: "player" }, { item: "ball", qty: 4 }],
    setup: "Everyone at one end, four with balls. Two catchers in the middle.",
    howItRuns:
      "Get to the far end without losing a tag. If you have a ball you must still be carrying it in two hands when you get there. Lose a tag and you become a catcher. Play until three are left. Everyone knows this game already, which means no explaining and straight into running.",
    coachingPoints: [
      "Pick a gap early and go hard at it",
      "Ball stays in two hands even when you are stepping",
      "Catchers spread out, do not bunch together",
    ],
    progressions: ["Everyone carries a ball", "Narrow the pitch"],
    regressions: ["Wider pitch", "One catcher to start"],
    faults: [
      {
        looks: "Waiting at the line for a gap that never comes",
        say: "Pick one early and go. Hesitating is how you get caught",
      },
      {
        looks: "The ball tucked under one arm as soon as they start stepping",
        say: "Two hands the whole way, even when you are dodging",
      },
    ],
  },
  {
    id: "drill-hit-the-hole",
    title: "Hit the hole",
    kind: "exercise",
    themes: ["evasion", "gamesense"],
    minAge: "u8",
    minutes: 9,
    players: { min: 8, max: 20 },
    space: "25 x 20 m",
    diagram: {
      space: [25, 20],
      cones: [[0, 0], [25, 0], [0, 20], [25, 20], [0, 10], [25, 10], [0, 16], [25, 16]],
      defence: [[3, 10], [8, 10], [13, 10], [22, 10]],
      attack: [[8, 17.5], [12, 17.5], [16, 17.5]],
      runs: [[[16, 16.4], [18.5, 3]]],
      passes: [[[8.95, 17.5], [11.05, 17.5]], [[12.95, 17.5], [15.05, 17.5]]],
      ball: [[8, 15.7]],
    },
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup: "Four defenders standing on a line with a gap somewhere between two of them. Attackers in threes.",
    howItRuns:
      "The defenders shuffle along their line and open a gap wherever they like. The attacking three have to spot it and get the ball to whoever can run through it. Defenders cannot move forward. Six goes then swap. They start looking at the defence instead of the ball.",
    coachingPoints: [
      "Somebody call the gap out loud. Do not all run at it",
      "Get the ball to whoever is closest to the space",
      "Straighten up and go through it, do not drift across",
    ],
    progressions: ["Defenders may take one step forward", "Only two attackers"],
    regressions: ["Bigger gap", "Defenders stand still"],
    faults: [
      {
        looks: "All three running at the same gap",
        say: "One person calls it. Everyone else does their own job",
      },
      {
        looks: "Drifting across the gap instead of through it",
        say: "Square up and go straight. Sideways runs into the cover",
      },
    ],
  },
  {
    id: "drill-shadow-and-step",
    title: "Shadow and step",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u8",
    minutes: 8,
    players: { min: 6, max: 18 },
    space: "15 x 15 m",
    diagram: {
      space: [15, 15],
      cones: [[0, 0], [15, 0], [0, 15], [15, 15]],
      defence: [[7.5, 10.5]],
      attack: [[7.5, 12.5]],
      runs: [[[8.6, 11.9], [11.5, 3], 1.5], [[6.2, 9.2], [9.2, 8.8]]],
      ball: [[7.5, 14.1]],
    },
    equipment: [{ item: "cone", qty: 4 }, { item: "ball", qty: 1, per: "pair" }],
    setup: "Pairs in a small grid. One carrier, one defender two metres in front.",
    howItRuns:
      "Carrier walks forward, defender mirrors them staying square. On your whistle the carrier steps and goes. Defender tries to stay in front. Thirty seconds then swap. Four each. Both of them get better at the same time, which is the nice thing about this one.",
    coachingPoints: [
      "Carriers, sell it with your shoulders before you move your feet",
      "Defenders stay square. Crossing your feet loses you the contest",
      "Both of you stay on the balls of your feet",
    ],
    progressions: ["Add a second carrier so the defender has a choice to make"],
    regressions: ["Walk the whole thing", "Bigger gap between them"],
    faults: [
      {
        looks: "The step made with the feet only, so nobody is fooled",
        say: "Drop your shoulder first. Sell it",
      },
      {
        looks: "Defenders crossing their feet and losing their balance",
        say: "Shuffle, do not cross. Stay square",
      },
    ],
  },
  {
    id: "drill-out-the-back-door",
    title: "Out the back door",
    kind: "exercise",
    themes: ["evasion", "handling"],
    minAge: "u8",
    minutes: 9,
    players: { min: 6, max: 18 },
    space: "20 x 15 m",
    diagram: {
      space: [15, 20],
      cones: [[0, 0], [15, 0], [0, 10], [15, 10], [0, 20], [15, 20]],
      defence: [[7, 9.5]],
      attack: [[7.5, 15.2], [4.5, 17], [10.5, 17]],
      runs: [[[7.5, 13.5], [7.5, 11]], [[10.5, 15.8], [12.5, 8.5]]],
      passes: [[[8.4, 15.6], [9.6, 16.6]]],
      ball: [[7.5, 13.7]],
    },
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "A carrier with two support runners, one on each shoulder. One defender in front.",
    howItRuns:
      "The carrier runs at the defender then gives it to either shoulder, whichever the defender has left open. The defender picks a side and commits. Six goes each. The lesson is that the defender chooses first and the attack just has to see it.",
    coachingPoints: [
      "Run at them properly. A defender who is not worried does not commit",
      "Wait for them to lean, then give it the other way",
      "Support runners keep depth so there is time to react",
    ],
    progressions: ["Two defenders", "Support runners cross behind the carrier"],
    regressions: ["Defender must commit early", "Walk it"],
    faults: [
      {
        looks: "Passing before the defender has committed to either side",
        say: "Wait. Watch which way they lean, then give it the other way",
      },
      {
        looks: "Both support runners flat alongside with no time to react",
        say: "Get deeper. You want a full second to see it",
      },
    ],
  },
  {
    id: "drill-one-on-one-channel",
    title: "One on one channel",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u8",
    minutes: 8,
    players: { min: 6, max: 20 },
    space: "10 x 20 m",
    diagram: {
      space: [10, 20],
      cones: [[0, 0], [10, 0], [0, 10], [10, 10], [0, 20], [10, 20]],
      defence: [[7.2, 5]],
      attack: [[5, 18.5]],
      runs: [[[5, 16.8], [8, 9.5]], [[8, 8.5], [3.5, 1.5]]],
      ball: [[5, 17]],
    },
    equipment: [{ item: "cone", qty: 6 }, { item: "tag", qty: 2, per: "player" }, { item: "ball", qty: 1 }],
    setup: "A narrow channel, one attacker at one end, one defender at the other.",
    howItRuns:
      "Straight race. Get to the other end with your tags. Narrow enough that footwork alone will not do it, so they have to change pace as well. Six goes each, alternate attacking and defending. Keep the pairs matched for size or the quick ones just run round everybody.",
    coachingPoints: [
      "Change of pace beats change of direction in a tight space",
      "Attack their outside shoulder then come back inside",
      "Defenders, do not dive in. Stay in front and force the decision",
    ],
    progressions: ["Narrower channel", "Defender starts closer"],
    regressions: ["Wider channel", "Defender may only move sideways"],
    faults: [
      {
        looks: "Running at one speed the whole way",
        say: "Slow down, then go. The change is what beats them",
      },
      {
        looks: "Defenders diving in and getting stepped",
        say: "Stay on your feet in front of them. Make them decide",
      },
    ],
  },
  {
    id: "drill-support-the-break",
    title: "Support the break",
    kind: "exercise",
    themes: ["evasion", "gamesense"],
    minAge: "u9",
    minutes: 10,
    players: { min: 8, max: 21 },
    space: "40 x 20 m",
    diagram: {
      space: [20, 40],
      cones: [[0, 0], [20, 0], [0, 40], [20, 40], [0, 26], [20, 26]],
      defence: [[8, 24], [14, 22]],
      attack: [[10, 33], [5, 36.5], [13.5, 36.5], [17, 39]],
      runs: [[[10, 30.4], [12.5, 14], 2], [[5, 34.8], [9.8, 21.5]]],
      ball: [[10, 30.6]],
    },
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "A carrier and three support runners spread behind. Two defenders in the middle third.",
    howItRuns:
      "The carrier beats the first defender then keeps going. Support has to get there before the second defender arrives. Score at the far end. Six goes. Making a break is the easy bit, having somebody with you when you do is what turns it into a try and that is a running habit rather than a skill.",
    coachingPoints: [
      "Support runs the moment the break happens, not once they are told",
      "Come from behind the ball, at an angle, not flat alongside",
      "Shout so the carrier knows you are there without looking",
    ],
    progressions: ["Three defenders", "Support starts further back"],
    regressions: ["One defender", "Support starts alongside the carrier"],
    faults: [
      {
        looks: "Support setting off once the carrier has already gone twenty metres",
        say: "Go when the break happens. Do not wait to be sure",
      },
      {
        looks: "Support running flat alongside so the pass has to go forward",
        say: "Come from behind at an angle. Deeper than that",
      },
    ],
  },
  {
    id: "drill-narrow-to-wide",
    title: "Narrow to wide",
    kind: "exercise",
    themes: ["evasion", "gamesense"],
    minAge: "u9",
    minutes: 10,
    players: { min: 10, max: 21 },
    space: "40 x 25 m",
    diagram: {
      space: [25, 40],
      cones: [
        [6, 40],
        [6, 34],
        [6, 27],
        [6, 20],
        [19, 40],
        [19, 34],
        [19, 27],
        [19, 20],
        [0, 20],
        [25, 20],
      ],
      defence: [[8.5, 28.5], [12.5, 27.5], [16.5, 28]],
      attack: [[9, 34.5], [12.8, 36.2], [16.5, 37.2], [22, 38.5]],
      runs: [[[22, 37.1], [23.5, 14], 1.5]],
      passes: [[[17.9, 37.5], [20.6, 38.1]]],
      ball: [[16.5, 34.6]],
    },
    equipment: [{ item: "cone", qty: 10 }, { item: "ball", qty: 1 }],
    setup:
      "A narrow channel that opens into a wide one halfway up. Four attackers, three defenders who must start in the narrow part.",
    howItRuns:
      "Attack has to get through the narrow bit then use the width once it opens. Defenders cannot leave the narrow channel until the ball does. Six goes then swap. It shows them that space is not something you find, it is something the shape of the game gives you if you wait for it.",
    coachingPoints: [
      "Hold the ball in tight until the space opens up",
      "Then move it fast and wide. Do not carry it there yourself",
      "Last player stays wide and stays quiet until they are needed",
    ],
    progressions: ["Four defenders", "Narrower first channel"],
    regressions: ["Five attackers", "Wider first channel"],
    faults: [
      {
        looks: "Carrying the ball out towards the touchline instead of passing it",
        say: "The ball goes wide, not you",
      },
      {
        looks: "The wide player shouting from the start and giving it away",
        say: "Stay quiet until the space is there",
      },
    ],
  },
  {
    id: "drill-kick-chase-regather",
    title: "Chase and regather",
    kind: "exercise",
    themes: ["evasion", "handling"],
    minAge: "u10",
    minutes: 9,
    players: { min: 6, max: 18 },
    space: "30 x 20 m",
    diagram: {
      label:
        "Set up diagram. The ball is rolled along the ground ahead of the chaser. They run onto it, gather it, then step past the one coming the other way.",
      space: [20, 30],
      cones: [[0, 0], [20, 0], [0, 30], [20, 30], [0, 8], [20, 8]],
      defence: [[4, 27], [12, 7]],
      attack: [[10, 25]],
      runs: [[[10, 23.6], [11.4, 16.2]], [[12.5, 12.5], [15.5, 3]], [[11.3, 8.6], [10.6, 11.3]]],
      passes: [[[4.6, 23.9], [11.4, 14.6]]],
      ball: [[4, 24.6], [12, 14]],
    },
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 2 }],
    setup: "A kicker at one end with the rest in a line beside them.",
    howItRuns:
      "The ball gets rolled or kicked along the floor ahead of them. They chase, gather it cleanly at pace, then beat one defender coming the other way. Six each. Picking up a loose ball while running flat out is a real skill and almost nobody practises it on purpose.",
    coachingPoints: [
      "Get down to it early. Do not reach at the last second",
      "Little fingers together, scoop it into your chest",
      "Have a look up before you get there so you know where the defender is",
    ],
    progressions: ["Ball is kicked so it bounces awkwardly", "Two chasers competing"],
    regressions: ["Roll it slowly", "No defender"],
    faults: [
      {
        looks: "Reaching down at the last stride and knocking it on",
        say: "Get down to it earlier. Two steps before, not one",
      },
      {
        looks: "Fingers apart so the ball goes through their hands",
        say: "Little fingers together. Scoop it into your chest",
      },
    ],
  },
  {
    id: "drill-two-touch-attack",
    title: "Two touch attack",
    kind: "exercise",
    themes: ["evasion", "gamesense"],
    minAge: "u10",
    minutes: 12,
    players: { min: 10, max: 24 },
    space: "40 x 25 m",
    diagram: {
      space: [25, 40],
      cones: [[0, 0], [25, 0], [0, 40], [25, 40], [0, 20], [25, 20]],
      defence: [[6, 22], [12, 21.5], [18, 22], [23, 23], [14, 25.5]],
      attack: [[5, 30], [11, 31], [17, 30.5], [22, 32], [13, 35]],
      runs: [[[17, 29], [15.5, 21]], [[22, 30.6], [20.5, 24.5]]],
      passes: [[[6.6, 30.2], [9.4, 30.8]], [[12.6, 31.1], [15.4, 30.7]]],
      ball: [[5, 27.4]],
    },
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "Two teams. Touch rules, two touches then the ball turns over.",
    howItRuns:
      "Only two touches before you lose it, so standing still is not an option. Play five minute halves. Then change it to three touches and watch how much lazier they get. That makes the point better than you telling them.",
    coachingPoints: [
      "Have your next move decided before the ball reaches you",
      "Somebody has to be running when the ball moves",
      "Two touches means two chances. Do not waste the first one",
    ],
    progressions: ["One touch only", "Narrow the pitch"],
    regressions: ["Four touches", "Wider pitch"],
    faults: [
      {
        looks: "Everybody stopping to think when the ball arrives",
        say: "Decide before it gets to you. What is your next move?",
      },
      {
        looks: "Nobody moving, so the second touch has nowhere to go",
        say: "Somebody has to be running every time the ball moves",
      },
    ],
  },
  {
    id: "drill-fend-and-go",
    title: "Fend and go",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u12",
    minutes: 9,
    players: { min: 6, max: 18 },
    space: "15 x 15 m",
    softGround: true,
    diagram: {
      space: [15, 15],
      shields: [[7.5, 7.5]],
      attack: [[7.5, 10.5]],
      runs: [[[8.4, 9.8], [12, 2], 1.8]],
      ball: [[6, 10]],
    },
    equipment: [{ item: "ball", qty: 1, per: "pair" }, { item: "tackle shield", qty: 1, per: "pair" }],
    setup: "Pairs. One holds a shield, the carrier walks at them from three metres.",
    howItRuns:
      "Ball in one hand, other hand out to push the shield away below the armpits, then accelerate past. Eight each. The hand off comes in at U12 so this is the first year it is legal and doing it too high is a penalty rather than a clever bit of play.",
    coachingPoints: [
      "Below the armpits. Anything higher is a penalty",
      "Push and go in one movement, do not stop to do it",
      "Ball tucked into the far arm before your other hand comes out",
    ],
    progressions: ["Jog into it", "Shield holder moves towards you"],
    regressions: ["Walk it", "Push the shield with no run afterwards"],
    safety:
      "The hand off stays below the armpits, never to the head or the neck. Shield holders absorb only. Walking pace until the height is right every time.",
    faults: [
      {
        looks: "The hand going up towards the head or the neck",
        say: "Below the armpits. Aim at their chest, nowhere higher",
      },
      {
        looks: "Stopping to push, so all the pace goes",
        say: "Push and run in the same movement. Do not plant your feet",
      },
    ],
  },
  {
    id: "drill-beat-the-drift",
    title: "Beat the drift",
    kind: "exercise",
    themes: ["evasion", "gamesense"],
    minAge: "u11",
    minutes: 11,
    players: { min: 10, max: 21 },
    space: "40 x 30 m",
    diagram: {
      space: [30, 40],
      cones: [[0, 0], [30, 0], [0, 40], [30, 40], [0, 20], [30, 20], [0, 32], [30, 32]],
      defence: [[8, 20], [14, 20], [20, 20], [26, 20]],
      attack: [[6, 34], [12, 35], [18, 36], [24, 37]],
      runs: [
        [[8, 21.4], [10.4, 23.2]],
        [[14, 21.4], [16.4, 23.2]],
        [[20, 21.4], [22.4, 23.2]],
        [[26, 21.4], [28.4, 23.2]],
        [[12, 33.6], [12, 21.8]],
      ],
      passes: [[[7.6, 34.3], [10.4, 34.7]]],
      ball: [[6, 31.4]],
    },
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup: "Four attackers against four defenders. Defenders told to drift across rather than come straight.",
    howItRuns:
      "The defence slides sideways to shut the width down. The attack has to either straighten up and go inside or move the ball quicker than the drift. Six goes each way then swap the roles. This is the puzzle their opponents will set them every week from about U11 onwards.",
    coachingPoints: [
      "One straight run inside stops the whole drift",
      "If the ball is slow the drift wins. Move it earlier",
      "Watch the outside defender's shoulders to see which way they are going",
    ],
    progressions: ["Defenders drift faster", "Five defenders against four"],
    regressions: ["Defenders come straight instead of drifting", "Five attackers"],
    faults: [
      {
        looks: "Everybody drifting the same way as the defence",
        say: "One of you run straight. That is what stops it",
      },
      {
        looks: "Slow ball, so the drift gets there first every time",
        say: "Earlier. Move it before they are set",
      },
    ],
  },
];
