import type { Drill } from "../types.js";

/** Footwork, finding space and beating a defender. See docs/content-sourcing.md. */
export const EVASION: Drill[] = [
  {
    id: "drill-tag-and-turn",
    title: "Tag and turn",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u7",
    maxAge: "u8",
    minutes: 8,
    players: { min: 6, max: 16 },
    space: "15 x 25 m",
    equipment: [
      { item: "cone", qty: 6 },
      { item: "tag", qty: 2, per: "player" },
      { item: "ball", qty: 1, per: "pair" },
    ],
    setup: "Attackers on one line. One defender in a five metre channel in front of them.",
    howItRuns:
      "Run at the defender and try to get past. The defender takes one tag and holds it up. If you lose a tag you stop, hand the ball on, then collect your tag and put it back before rejoining. Rotate the defender every four goes.",
    coachingPoints: [
      "Change your angle before you get within reach, not after",
      "Defenders watch the hips, not the ball or the head",
      "Hold the tag up straight away so the referee sees it",
    ],
    progressions: ["Two defenders in the channel"],
    regressions: ["Walk it through", "Wider channel"],
  },
  {
    id: "drill-gate-choice",
    title: "Pick your gate",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u7",
    minutes: 8,
    players: { min: 6, max: 20 },
    space: "20 x 15 m",
    equipment: [{ item: "cone", qty: 10 }, { item: "ball", qty: 1 }],
    setup: "Three gates side by side across a channel, three metres wide each. A defender behind them.",
    howItRuns:
      "Run at the gates with the ball. The defender picks one gate to stand in. You go through a different one. Eight goes each. That is it. All you want is a child who looks up and chooses instead of running at whoever is in front of them.",
    coachingPoints: [
      "Look up before you run, then pick",
      "Commit to your gate. Changing your mind late gets you caught",
      "Ball in two hands so you are ready to do something else",
    ],
    progressions: ["Defender starts moving before you set off", "Two defenders in three gates"],
    regressions: ["Four gates", "Defender stands still until you commit"],
  },
  {
    id: "drill-side-step-slalom",
    title: "Side step slalom",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u7",
    minutes: 7,
    players: { min: 4 },
    space: "20 m channel",
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup: "Eight cones in a line, two metres apart, up a channel.",
    howItRuns:
      "Run the line and step off the outside foot at every cone. Walk it once, jog it twice, then run it. Four goes each. It teaches the mechanics with nobody chasing them, so when somebody is chasing them the feet already know what to do.",
    coachingPoints: [
      "Push off the outside foot, do not just lean over",
      "Short choppy steps as you get near the cone",
      "Head and eyes stay up the pitch",
    ],
    progressions: ["Carry a ball", "A defender stands at the last cone"],
    regressions: ["Wider spacing", "Walk it all the way through"],
  },
  {
    id: "drill-british-bulldog-ball",
    title: "Bulldog with a ball",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u7",
    minutes: 9,
    players: { min: 8, max: 24 },
    space: "25 x 20 m",
    equipment: [{ item: "cone", qty: 6 }, { item: "tag", qty: 2, per: "player" }, { item: "ball", qty: 4 }],
    setup: "Everyone at one end, four with balls. Two catchers in the middle.",
    howItRuns:
      "Get to the far end without losing a tag. If you have a ball you must still be carrying it in two hands when you get there. Lose a tag and you become a catcher. Play until three are left. Everyone knows this game already, which means no explaining and straight into running.",
    coachingPoints: [
      "Pick a gap early and go hard at it",
      "Ball stays in two hands even when you are stepping",
      "Catchers spread out, do not bunch together",
    ],
    progressions: ["Everyone carries a ball", "Narrow the pitch"],
    regressions: ["Wider pitch", "One catcher to start"],
  },
  {
    id: "drill-hit-the-hole",
    title: "Hit the hole",
    kind: "exercise",
    themes: ["evasion", "gamesense"],
    minAge: "u8",
    minutes: 9,
    players: { min: 8, max: 20 },
    space: "25 x 20 m",
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup: "Four defenders standing on a line with a gap somewhere between two of them. Attackers in threes.",
    howItRuns:
      "The defenders shuffle along their line and open a gap wherever they like. The attacking three have to spot it and get the ball to whoever can run through it. Defenders cannot move forward. Six goes then swap. They start looking at the defence instead of the ball.",
    coachingPoints: [
      "Somebody call the gap out loud. Do not all run at it",
      "Get the ball to whoever is closest to the space",
      "Straighten up and go through it, do not drift across",
    ],
    progressions: ["Defenders may take one step forward", "Only two attackers"],
    regressions: ["Bigger gap", "Defenders stand still"],
  },
  {
    id: "drill-shadow-and-step",
    title: "Shadow and step",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u8",
    minutes: 8,
    players: { min: 6, max: 18 },
    space: "15 x 15 m",
    equipment: [{ item: "cone", qty: 4 }, { item: "ball", qty: 1, per: "pair" }],
    setup: "Pairs in a small grid. One carrier, one defender two metres in front.",
    howItRuns:
      "Carrier walks forward, defender mirrors them staying square. On your whistle the carrier steps and goes. Defender tries to stay in front. Thirty seconds then swap. Four each. Both of them get better at the same time, which is the nice thing about this one.",
    coachingPoints: [
      "Carriers, sell it with your shoulders before you move your feet",
      "Defenders stay square. Crossing your feet loses you the contest",
      "Both of you stay on the balls of your feet",
    ],
    progressions: ["Add a second carrier so the defender has a choice to make"],
    regressions: ["Walk the whole thing", "Bigger gap between them"],
  },
  {
    id: "drill-out-the-back-door",
    title: "Out the back door",
    kind: "exercise",
    themes: ["evasion", "handling"],
    minAge: "u8",
    minutes: 9,
    players: { min: 6, max: 18 },
    space: "20 x 15 m",
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "A carrier with two support runners, one on each shoulder. One defender in front.",
    howItRuns:
      "The carrier runs at the defender then gives it to either shoulder, whichever the defender has left open. The defender picks a side and commits. Six goes each. The lesson is that the defender chooses first and the attack just has to see it.",
    coachingPoints: [
      "Run at them properly. A defender who is not worried does not commit",
      "Wait for them to lean, then give it the other way",
      "Support runners keep depth so there is time to react",
    ],
    progressions: ["Two defenders", "Support runners cross behind the carrier"],
    regressions: ["Defender must commit early", "Walk it"],
  },
  {
    id: "drill-one-on-one-channel",
    title: "One on one channel",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u8",
    minutes: 8,
    players: { min: 6, max: 20 },
    space: "10 x 20 m",
    equipment: [{ item: "cone", qty: 6 }, { item: "tag", qty: 2, per: "player" }, { item: "ball", qty: 1 }],
    setup: "A narrow channel, one attacker at one end, one defender at the other.",
    howItRuns:
      "Straight race. Get to the other end with your tags. Narrow enough that footwork alone will not do it, so they have to change pace as well. Six goes each, alternate attacking and defending. Keep the pairs matched for size or the quick ones just run round everybody.",
    coachingPoints: [
      "Change of pace beats change of direction in a tight space",
      "Attack their outside shoulder then come back inside",
      "Defenders, do not dive in. Stay in front and force the decision",
    ],
    progressions: ["Narrower channel", "Defender starts closer"],
    regressions: ["Wider channel", "Defender may only move sideways"],
  },
  {
    id: "drill-support-the-break",
    title: "Support the break",
    kind: "exercise",
    themes: ["evasion", "gamesense"],
    minAge: "u9",
    minutes: 10,
    players: { min: 8, max: 21 },
    space: "40 x 20 m",
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "A carrier and three support runners spread behind. Two defenders in the middle third.",
    howItRuns:
      "The carrier beats the first defender then keeps going. Support has to get there before the second defender arrives. Score at the far end. Six goes. Making a break is the easy bit, having somebody with you when you do is what turns it into a try and that is a running habit rather than a skill.",
    coachingPoints: [
      "Support runs the moment the break happens, not once they are told",
      "Come from behind the ball, at an angle, not flat alongside",
      "Shout so the carrier knows you are there without looking",
    ],
    progressions: ["Three defenders", "Support starts further back"],
    regressions: ["One defender", "Support starts alongside the carrier"],
  },
  {
    id: "drill-narrow-to-wide",
    title: "Narrow to wide",
    kind: "exercise",
    themes: ["evasion", "gamesense"],
    minAge: "u9",
    minutes: 10,
    players: { min: 10, max: 21 },
    space: "40 x 25 m",
    equipment: [{ item: "cone", qty: 10 }, { item: "ball", qty: 1 }],
    setup:
      "A narrow channel that opens into a wide one halfway up. Four attackers, three defenders who must start in the narrow part.",
    howItRuns:
      "Attack has to get through the narrow bit then use the width once it opens. Defenders cannot leave the narrow channel until the ball does. Six goes then swap. It shows them that space is not something you find, it is something the shape of the game gives you if you wait for it.",
    coachingPoints: [
      "Hold the ball in tight until the space opens up",
      "Then move it fast and wide. Do not carry it there yourself",
      "Last player stays wide and stays quiet until they are needed",
    ],
    progressions: ["Four defenders", "Narrower first channel"],
    regressions: ["Five attackers", "Wider first channel"],
  },
  {
    id: "drill-kick-chase-regather",
    title: "Chase and regather",
    kind: "exercise",
    themes: ["evasion", "handling"],
    minAge: "u10",
    minutes: 9,
    players: { min: 6, max: 18 },
    space: "30 x 20 m",
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 2 }],
    setup: "A kicker at one end with the rest in a line beside them.",
    howItRuns:
      "The ball gets rolled or kicked along the floor ahead of them. They chase, gather it cleanly at pace, then beat one defender coming the other way. Six each. Picking up a loose ball while running flat out is a real skill and almost nobody practises it on purpose.",
    coachingPoints: [
      "Get down to it early. Do not reach at the last second",
      "Little fingers together, scoop it into your chest",
      "Have a look up before you get there so you know where the defender is",
    ],
    progressions: ["Ball is kicked so it bounces awkwardly", "Two chasers competing"],
    regressions: ["Roll it slowly", "No defender"],
  },
  {
    id: "drill-two-touch-attack",
    title: "Two touch attack",
    kind: "exercise",
    themes: ["evasion", "gamesense"],
    minAge: "u10",
    minutes: 12,
    players: { min: 10, max: 24 },
    space: "40 x 25 m",
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "Two teams. Touch rules, two touches then the ball turns over.",
    howItRuns:
      "Only two touches before you lose it, so standing still is not an option. Play five minute halves. Then change it to three touches and watch how much lazier they get. That makes the point better than you telling them.",
    coachingPoints: [
      "Have your next move decided before the ball reaches you",
      "Somebody has to be running when the ball moves",
      "Two touches means two chances. Do not waste the first one",
    ],
    progressions: ["One touch only", "Narrow the pitch"],
    regressions: ["Four touches", "Wider pitch"],
  },
  {
    id: "drill-fend-and-go",
    title: "Fend and go",
    kind: "exercise",
    themes: ["evasion"],
    minAge: "u12",
    minutes: 9,
    players: { min: 6, max: 18 },
    space: "15 x 15 m",
    equipment: [{ item: "ball", qty: 1, per: "pair" }, { item: "tackle shield", qty: 1, per: "pair" }],
    setup: "Pairs. One holds a shield, the carrier walks at them from three metres.",
    howItRuns:
      "Ball in one hand, other hand out to push the shield away below the armpits, then accelerate past. Eight each. The hand off comes in at U12 so this is the first year it is legal and doing it too high is a penalty rather than a clever bit of play.",
    coachingPoints: [
      "Below the armpits. Anything higher is a penalty",
      "Push and go in one movement, do not stop to do it",
      "Ball tucked into the far arm before your other hand comes out",
    ],
    progressions: ["Jog into it", "Shield holder moves towards you"],
    regressions: ["Walk it", "Push the shield with no run afterwards"],
    safety:
      "The hand off stays below the armpits, never to the head or the neck. Shield holders absorb only. Walking pace until the height is right every time.",
  },
  {
    id: "drill-beat-the-drift",
    title: "Beat the drift",
    kind: "exercise",
    themes: ["evasion", "gamesense"],
    minAge: "u11",
    minutes: 11,
    players: { min: 10, max: 21 },
    space: "40 x 30 m",
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup: "Four attackers against four defenders. Defenders told to drift across rather than come straight.",
    howItRuns:
      "The defence slides sideways to shut the width down. The attack has to either straighten up and go inside or move the ball quicker than the drift. Six goes each way then swap the roles. This is the puzzle their opponents will set them every week from about U11 onwards.",
    coachingPoints: [
      "One straight run inside stops the whole drift",
      "If the ball is slow the drift wins. Move it earlier",
      "Watch the outside defender's shoulders to see which way they are going",
    ],
    progressions: ["Defenders drift faster", "Five defenders against four"],
    regressions: ["Defenders come straight instead of drifting", "Five attackers"],
  },
];
