import type { Drill } from "../types.js";

/**
 * Conditioned games and decision making. See docs/content-sourcing.md.
 *
 * Most of these are games with one rule changed. That is deliberate. Children learn
 * to make decisions by making them, not by being told what the right one was.
 */
export const GAMESENSE: Drill[] = [
  {
    id: "drill-end-ball",
    title: "End ball",
    kind: "exercise",
    themes: ["gamesense", "handling"],
    minAge: "u7",
    minutes: 10,
    players: { min: 8, max: 24 },
    space: "25 x 20 m",
    diagram: {
      space: [25, 20],
      cones: [[0, 0], [8, 0], [17, 0], [25, 0], [0, 20], [8, 20], [17, 20], [25, 20]],
      defence: [[8.5, 9], [13.5, 8.5], [18.5, 9], [22.5, 10]],
      attack: [[6, 15], [11, 14], [16, 14.5], [21, 15.5]],
      runs: [[[6, 13.9], [6, 5]], [[11, 12.9], [11, 5]]],
      passes: [
        [[7.1, 14.8], [9.9, 14.2]],
        [[12.1, 14.1], [14.9, 14.4]],
        [[17.1, 14.6], [19.9, 15.4]],
      ],
      ball: [[3.9, 15.6]],
    },
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup: "Two teams, a try line at each end. One ball.",
    howItRuns:
      "Touch rules. Score by putting the ball down over the line. Nobody may run with the ball at all, so it can only move by passing. Four minute games. Taking running out of it means everybody has to move into space to be useful, which is the habit you actually want.",
    coachingPoints: [
      "Move as soon as you have passed it",
      "Get in front of the ball but not offside",
      "Shout for it when you are free",
    ],
    progressions: ["Three steps allowed with the ball", "Two balls at once"],
    regressions: ["Bigger pitch", "More players on the attacking team"],
  },
  {
    id: "drill-four-goals",
    title: "Four goals",
    kind: "exercise",
    themes: ["gamesense"],
    minAge: "u7",
    minutes: 10,
    players: { min: 8, max: 20 },
    space: "25 x 25 m",
    diagram: {
      space: [25, 25],
      cones: [
        [0, 0],
        [25, 0],
        [0, 25],
        [25, 25],
        [11.5, 0],
        [13.5, 0],
        [11.5, 25],
        [13.5, 25],
        [0, 11.5],
        [0, 13.5],
        [25, 11.5],
        [25, 13.5],
      ],
      defence: [[11, 12], [16, 12], [7, 11], [21, 16.8]],
      attack: [[11, 19], [16, 17], [7, 15], [19, 21]],
      runs: [[[16, 16], [24, 13.2]], [[7, 14], [12.3, 1.6]]],
      passes: [[[12, 18.7], [15, 17.4]]],
      ball: [[9, 19.8]],
    },
    equipment: [{ item: "cone", qty: 12 }, { item: "ball", qty: 1 }],
    setup: "A square with a two metre goal in the middle of each side. Two teams.",
    howItRuns:
      "Score through any of the four goals. Touch rules. Because there is no fixed direction they cannot just charge one way, they have to look around and pick. Five minute games. Watch how long it takes before somebody works out that turning round is allowed.",
    coachingPoints: [
      "Look for the goal nobody is guarding",
      "Turning back the way you came is allowed and often best",
      "Talk to each other about which one you are going for",
    ],
    progressions: ["Add a fifth goal in a corner", "Shrink the square"],
    regressions: ["Two goals only", "Bigger square"],
  },
  {
    id: "drill-keep-ball-count",
    title: "Keep ball",
    kind: "exercise",
    themes: ["gamesense", "handling"],
    minAge: "u7",
    minutes: 8,
    players: { min: 8, max: 20 },
    space: "20 x 20 m",
    diagram: {
      space: [20, 20],
      cones: [[0, 0], [20, 0], [0, 20], [20, 20]],
      defence: [[7.5, 10], [13, 15], [16, 7.5], [11, 18]],
      attack: [[5, 13], [10, 16], [15, 12], [9, 7]],
      passes: [
        [[5.8, 13.5], [9.2, 15.5]],
        [[10.7, 15.4], [14.3, 12.6]],
        [[14.3, 11.4], [9.7, 7.6]],
      ],
      ball: [[3.4, 13.4]],
    },
    equipment: [{ item: "cone", qty: 4 }, { item: "ball", qty: 1 }],
    setup: "Two teams in a square, no try lines at all.",
    howItRuns:
      "Six passes in a row is a point. Touch rules, a touch turns the ball over. First to three points. There is nowhere to run to so the only thing they can do is keep it, which is the skill that makes everything else possible.",
    coachingPoints: [
      "Somebody has to be free before the pass is needed",
      "Count out loud together so everybody knows where you are",
      "Short pass to a free player beats a long one to a marked one",
    ],
    progressions: ["Eight passes", "Smaller square"],
    regressions: ["Four passes", "One extra attacker"],
  },
  {
    id: "drill-two-ball-chaos",
    title: "Two ball chaos",
    kind: "exercise",
    themes: ["gamesense"],
    minAge: "u8",
    minutes: 9,
    players: { min: 10, max: 24 },
    space: "30 x 25 m",
    diagram: {
      label:
        "Set up diagram. Two teams with a ball each, attacking opposite try lines at the same time.",
      space: [30, 25],
      cones: [[0, 0], [10, 0], [20, 0], [30, 0], [0, 25], [10, 25], [20, 25], [30, 25]],
      defence: [[9, 10], [14, 11], [19, 10], [24, 11], [27, 13]],
      attack: [[6, 16], [11, 15], [16, 16], [21, 15], [25, 17]],
      runs: [[[11, 13.8], [10, 4]], [[14, 12.2], [15, 21]]],
      ball: [[3.6, 16.6], [21.4, 9.4]],
    },
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 2 }],
    setup: "Two teams, two balls, one each. Try lines at both ends.",
    howItRuns:
      "Both teams attack at the same time with their own ball. Touch rules. Nobody gets to stand and watch because their own ball is always live. Five minute games. It is noisy and slightly mad. They will love it and it fixes ball watching in about two sessions.",
    coachingPoints: [
      "Know where your own ball is at all times",
      "Do not chase the other team's ball, it is not yours",
      "Use the space they have left behind them",
    ],
    progressions: ["Three balls", "Narrower pitch"],
    regressions: ["Take the second ball out for a few minutes", "Bigger pitch"],
  },
  {
    id: "drill-defend-the-line",
    title: "Defend the line",
    kind: "exercise",
    themes: ["gamesense"],
    minAge: "u8",
    minutes: 10,
    players: { min: 10, max: 24 },
    space: "30 x 25 m",
    diagram: {
      space: [30, 25],
      cones: [[0, 0], [30, 0], [0, 25], [30, 25], [0, 12], [30, 12]],
      defence: [[8, 12], [14, 12], [19, 12], [25, 12]],
      attack: [[6, 18], [12, 18.6], [18, 19], [23, 19.6], [27, 20]],
      runs: [[[19, 13.2], [19, 17]], [[23, 18.4], [20.5, 3]]],
      passes: [
        [[7.2, 18.1], [10.8, 18.5]],
        [[13.2, 18.7], [16.8, 18.9]],
        [[19.2, 19.1], [21.8, 19.4]],
      ],
      ball: [[3.6, 18.6]],
    },
    equipment: [{ item: "cone", qty: 6 }, { item: "tag", qty: 2, per: "player" }, { item: "ball", qty: 1 }],
    setup: "Five attackers against four defenders, defenders on a marked line.",
    howItRuns:
      "The attack has three goes to score. The defenders can only move once the ball moves. Then swap. Give the defenders one instruction only, which is to stay in a line and let them find out for themselves what happens when one of them rushes out.",
    coachingPoints: [
      "Defenders come up together. One out on their own leaves a hole",
      "Talk along the line. Say who you have got",
      "Attackers, find the one who came up too fast",
    ],
    progressions: ["Six attackers against four", "Defenders start further back"],
    regressions: ["Even numbers", "Defenders may move as soon as the attack sets off"],
  },
  {
    id: "drill-ten-metre-decisions",
    title: "Ten metres to decide",
    kind: "exercise",
    themes: ["gamesense"],
    minAge: "u8",
    minutes: 9,
    players: { min: 8, max: 20 },
    space: "20 x 20 m",
    diagram: {
      space: [20, 20],
      cones: [[0, 0], [7, 0], [13, 0], [20, 0], [0, 10], [7, 10], [13, 10], [20, 10]],
      defence: [[9, 5], [14, 5]],
      attack: [[6, 10.5], [10, 11], [14, 11.5]],
      runs: [[[6, 9.4], [5.5, 1.8]], [[14, 10.4], [16.5, 1.8]]],
      passes: [[[6.9, 10.6], [9.1, 10.9]], [[10.9, 11.1], [13.1, 11.4]]],
      ball: [[3.8, 11]],
    },
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup: "Threes attacking, two defenders, only ten metres of pitch to work in.",
    howItRuns:
      "Score in ten metres. There is no time to think about it so they have to have looked before the ball arrives. Six goes then rotate. Short and sharp. Much more like a real match than a long open drill where everybody has ages.",
    coachingPoints: [
      "Look at the defence before you get the ball, not after",
      "First decision is usually the right one at this distance",
      "Do not step sideways. There is no room for it",
    ],
    progressions: ["Eight metres", "Three defenders"],
    regressions: ["Fifteen metres", "One defender"],
  },
  {
    id: "drill-turnover-game",
    title: "Turnover game",
    kind: "exercise",
    themes: ["gamesense"],
    minAge: "u9",
    minutes: 12,
    players: { min: 10, max: 24 },
    space: "35 x 25 m",
    diagram: {
      space: [35, 25],
      cones: [[0, 0], [17.5, 0], [35, 0], [0, 25], [17.5, 25], [35, 25]],
      defence: [[8, 17], [14, 19], [20, 18.5], [25, 19], [30, 6]],
      attack: [[11, 14.5], [16, 13], [21, 14], [26, 15]],
      runs: [[[16, 11.5], [15, 2.5]], [[21, 12.5], [21, 4]], [[28.7, 5.5], [24, 2]]],
      passes: [[[17.4, 13.3], [19.6, 13.9]]],
      ball: [[13.4, 12.4]],
    },
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "Two teams, normal touch rules, try lines at both ends.",
    howItRuns:
      "Every time the ball turns over, whoever wins it has five seconds where the other team cannot touch them. Five minute halves. It teaches both sides the same lesson, which is that the moment right after a turnover is the best chance either team gets all game.",
    coachingPoints: [
      "Winning the ball back is only useful if you go somewhere with it",
      "Look up the instant you get it. The space is there now, not in ten seconds",
      "Defending team, get back and reset fast",
    ],
    progressions: ["Three seconds instead of five", "Narrower pitch"],
    regressions: ["Seven seconds", "Bigger pitch"],
  },
  {
    id: "drill-scoring-zones",
    title: "Scoring zones",
    kind: "exercise",
    themes: ["gamesense"],
    minAge: "u9",
    minutes: 11,
    players: { min: 10, max: 24 },
    space: "35 x 30 m",
    diagram: {
      space: [35, 30],
      zones: [["tl", 10], ["tr", 10]],
      cones: [
        [0, 0],
        [35, 0],
        [0, 30],
        [35, 30],
        [10, 0],
        [25, 0],
        [10, 10],
        [25, 10],
        [0, 10],
        [35, 10],
      ],
      defence: [[12, 12], [18, 12.5], [24, 13], [29, 13.5]],
      attack: [[14, 16], [19, 17], [25, 18], [31, 19]],
      runs: [[[31, 17.3], [32, 2.5]]],
      passes: [
        [[15.2, 16.2], [17.8, 16.8]],
        [[20.3, 17.3], [23.7, 17.7]],
        [[26.2, 18.2], [29.8, 18.8]],
      ],
      ball: [[11.2, 16.6]],
    },
    equipment: [{ item: "cone", qty: 10 }, { item: "ball", qty: 1 }],
    setup: "A try line split into three zones. The two outside zones are worth three, the middle worth one.",
    howItRuns:
      "Normal touch rules, but where you score matters. Five minute games. Nobody needs telling to use the width once there are points in it, which is a lot easier than shouting spread out for twenty minutes.",
    coachingPoints: [
      "Set off towards the middle then move it wide",
      "The wide player stays wide. Do not drift in to be involved",
      "One point is still a point if the wide zone is covered",
    ],
    progressions: ["Five in the wide zones and one in the middle", "Narrower middle zone"],
    regressions: ["Two in the wide zones", "Wider pitch"],
  },
  {
    id: "drill-no-talking-game",
    title: "The quiet game",
    kind: "exercise",
    themes: ["gamesense"],
    minAge: "u9",
    minutes: 8,
    players: { min: 10, max: 24 },
    space: "30 x 25 m",
    diagram: {
      space: [30, 25],
      cones: [[0, 0], [15, 0], [30, 0], [0, 25], [15, 25], [30, 25]],
      defence: [[5, 9], [11, 9], [17, 9], [23, 9], [28, 9]],
      attack: [[15, 15], [10, 17.5], [4, 20], [20, 17.5], [26, 20]],
      runs: [[[4, 18.8], [8, 3]], [[26, 18.8], [25.5, 3]]],
      passes: [[[16.3, 15.65], [18.7, 16.85]]],
      ball: [[12.5, 13.8]],
    },
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "Two teams, normal touch rules.",
    howItRuns:
      "Four minutes with nobody allowed to say a word. Then four minutes where they can talk as much as they like. Do not explain why beforehand. Ask them afterwards which half was better and they will tell you themselves, which is worth more than any amount of you asking for communication.",
    coachingPoints: [
      "In the quiet half, look at each other more",
      "In the loud half, say something useful not just noise",
      "Short calls. A name and a word",
    ],
    progressions: ["Only the ball carrier may speak"],
    regressions: ["Two minutes each way"],
  },
  {
    id: "drill-outnumbered-defence",
    title: "Outnumbered defence",
    kind: "exercise",
    themes: ["gamesense"],
    minAge: "u10",
    minutes: 11,
    players: { min: 9, max: 21 },
    space: "30 x 25 m",
    diagram: {
      space: [30, 25],
      cones: [[0, 0], [30, 0], [0, 25], [30, 25], [0, 12], [30, 12]],
      defence: [[9, 12], [15, 12], [21, 12]],
      attack: [[7, 18], [13, 18.5], [19, 19], [25, 19.5]],
      runs: [[[21, 13.1], [24, 16.6]]],
      passes: [
        [[8.2, 18.1], [11.8, 18.4]],
        [[14.2, 18.6], [17.8, 18.9]],
        [[20.2, 19.1], [23.8, 19.4]],
      ],
      ball: [[4.6, 18.6]],
    },
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "Four attackers against three defenders. Defenders on a line.",
    howItRuns:
      "The defence is always a player short, so somebody has to cover two. Six goes then swap. They will not stop the attack every time and that is fine. What you want is three defenders who slow it down and force a mistake rather than three who all rush the ball.",
    coachingPoints: [
      "Do not all go for the carrier. Somebody has to hold the outside",
      "Slow it down. You do not have to stop it in the first two seconds",
      "Talk. The player covering two needs to know which one to take",
    ],
    progressions: ["Five against three", "Bigger pitch so there is more to cover"],
    regressions: ["Four against four", "Narrower pitch"],
  },
  {
    id: "drill-three-phase-game",
    title: "Three phase game",
    kind: "exercise",
    themes: ["gamesense", "breakdown"],
    minAge: "u10",
    minutes: 12,
    players: { min: 12, max: 24 },
    space: "40 x 30 m",
    diagram: {
      space: [40, 30],
      cones: [[0, 0], [13, 0], [27, 0], [40, 0], [0, 30], [13, 30], [27, 30], [40, 30]],
      defence: [[13.5, 13.5], [17, 13.5], [24, 12.5], [29, 12.5], [34, 13], [39, 13.5]],
      attack: [[13.5, 17], [17, 17], [18, 20.5], [25, 17.5], [31, 18], [37, 18.5]],
      runs: [[[31, 16.2], [31.5, 7]], [[37, 16.7], [36, 7]]],
      passes: [
        [[19.5, 20.1], [23.5, 18]],
        [[26.6, 17.6], [29.4, 17.9]],
        [[32.6, 18.1], [35.4, 18.4]],
      ],
      ball: [[15, 20]],
    },
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup: "Two teams playing contact rugby with normal age grade rules.",
    howItRuns:
      "You get exactly three rucks before the ball turns over, so a try has to come inside that. Five minute halves. It stops the endless one metre carries and makes them think about where the next phase is going before they get there.",
    coachingPoints: [
      "Decide where phase two is going while phase one is still happening",
      "Get the ball away from the ruck quickly. Slow ball wastes a phase",
      "Do not put everybody into the first ruck",
    ],
    progressions: ["Two phases only", "Narrower pitch"],
    regressions: ["Five phases", "Touch rules instead of contact"],
    safety:
      "Age grade contact rules apply exactly as they do on a Sunday. Nobody off their feet at the ruck, nobody joining from the side and stop it if heads start dropping through tiredness.",
  },
  {
    id: "drill-space-then-contact",
    title: "Space then contact",
    kind: "exercise",
    themes: ["gamesense"],
    minAge: "u11",
    minutes: 12,
    players: { min: 12, max: 24 },
    space: "40 x 30 m",
    diagram: {
      space: [40, 30],
      cones: [
        [0, 0],
        [40, 0],
        [0, 30],
        [40, 30],
        [0, 15],
        [8, 15],
        [16, 15],
        [24, 15],
        [32, 15],
        [40, 15],
      ],
      defence: [[11, 18], [18, 18], [26, 18.5], [31, 8]],
      attack: [[8, 22], [15, 22.5], [22, 23], [29, 23.5]],
      runs: [[[29, 22], [30.5, 10.5]]],
      passes: [
        [[9.6, 22.1], [13.4, 22.4]],
        [[16.6, 22.6], [20.4, 22.9]],
        [[23.6, 23.1], [27.4, 23.4]],
      ],
      ball: [[5, 22.6]],
    },
    equipment: [{ item: "cone", qty: 10 }, { item: "ball", qty: 1 }],
    setup:
      "A pitch split down the middle. One half is touch only, the other half allows contact. Two teams.",
    howItRuns:
      "Move the ball through the touch half then it is contact once you cross the line. Five minute halves, then swap which half is which. Children default to running into people. This makes them use their hands first because in that half there is no other option.",
    coachingPoints: [
      "Use your hands while you have the space to",
      "Pick who takes the contact before you get there",
      "Contact is a choice, not what happens when you run out of ideas",
    ],
    progressions: ["Two thirds touch, one third contact", "Narrower pitch"],
    regressions: ["Touch everywhere", "Bigger pitch"],
    safety:
      "Age grade contact rules in the contact half. Watch for anybody carrying the touch-half habits into contact with a bad body position.",
  },
  {
    id: "drill-last-play",
    title: "Last play",
    kind: "exercise",
    themes: ["gamesense"],
    minAge: "u11",
    minutes: 10,
    players: { min: 12, max: 24 },
    space: "40 x 30 m",
    diagram: {
      space: [40, 30],
      cones: [[0, 0], [20, 0], [40, 0], [0, 30], [20, 30], [40, 30]],
      defence: [[5, 20], [11, 20], [17, 20], [24, 20], [30, 20], [36, 20]],
      attack: [[8, 28], [14, 28], [20, 28], [26, 28], [32, 28], [38, 28]],
      runs: [[[20, 26.1], [19, 2], 2.5]],
      passes: [[[9.6, 28], [12.4, 28]], [[15.6, 28], [18.4, 28]]],
      ball: [[4.8, 28.4]],
    },
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "Two teams. One team starts thirty metres out, needing a try.",
    howItRuns:
      "One play, one score needed, everything on it. Then reset and the other team goes. Ten goes each. Pressure is a skill like any other and a child who has practised the last play of a game is a lot calmer when it actually is the last play of a game.",
    coachingPoints: [
      "Agree the plan before you start. There is no time to work it out",
      "Nobody panics and kicks it. Keep hold of it",
      "Defending team, do not give away a penalty. Just hold your line",
    ],
    progressions: ["Twenty metres out with two defenders extra"],
    regressions: ["Two plays instead of one", "Even numbers"],
  },
  {
    id: "drill-back-three-cover",
    title: "Covering the back",
    kind: "exercise",
    themes: ["gamesense"],
    minAge: "u12",
    minutes: 10,
    players: { min: 8, max: 20 },
    space: "40 x 30 m",
    diagram: {
      label:
        "Set up diagram. Three players spread across the back of the pitch turning to cover a ball put in behind them.",
      space: [40, 30],
      cones: [[0, 0], [40, 0], [0, 30], [40, 30], [0, 18], [40, 18]],
      attack: [[8, 18], [20, 18], [32, 18]],
      runs: [[[20, 16.2], [15, 9.5]], [[8, 16.2], [11, 11]], [[32, 16.2], [22, 12]]],
      ball: [[13.5, 7]],
    },
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 2 }],
    setup: "Three defenders spread across the back of the pitch. You put balls in behind them.",
    howItRuns:
      "Kick or throw the ball into the space behind them. They have to cover it, communicate, get it back under control. Ten goes to different parts of the pitch. Nobody coaches this at minis level and it is where the soft tries come from.",
    coachingPoints: [
      "One voice calls who is taking it. Use a name",
      "The other two get either side of the catcher",
      "Turn and face up the pitch before you do anything with it",
    ],
    progressions: ["Add two chasers", "Balls that bounce awkwardly"],
    regressions: ["Roll it along the ground", "Nominate the catcher first"],
  },
  {
    id: "drill-full-game-conditions",
    title: "Sunday conditions",
    kind: "exercise",
    themes: ["gamesense"],
    minAge: "u12",
    minutes: 15,
    players: { min: 14, max: 24 },
    space: "60 x 43 m",
    diagram: {
      space: [43, 60],
      cones: [
        [0, 0],
        [21.5, 0],
        [43, 0],
        [0, 60],
        [21.5, 60],
        [43, 60],
        [0, 30],
        [43, 30],
        [0, 22],
        [43, 22],
        [0, 38],
        [43, 38],
      ],
      defence: [[4, 31], [10, 31], [16, 31], [22, 31], [28, 31], [33, 31], [38, 31]],
      attack: [[5, 38], [11, 38.5], [17, 39], [23, 39.5], [29, 40], [35, 40.5], [40, 41]],
      runs: [[[40.2, 37.5], [41, 5], 2]],
      ball: [[1.5, 41.5]],
    },
    equipment: [{ item: "cone", qty: 12 }, { item: "ball", qty: 2 }],
    setup: "Full age grade pitch, full age grade rules, proper teams. A referee who blows for everything.",
    howItRuns:
      "Just play. Fifteen minutes with the actual rules of play for your age grade, including the scrum, refereed properly. Nothing conditioned. Stop it twice, no more and only for something that will happen again on Sunday. The last thing they should do most weeks is play rugby.",
    coachingPoints: [
      "Play what is in front of you",
      "Keep talking through the stoppages, not just in open play",
      "Every restart is a chance. Be organised before the whistle",
    ],
    progressions: ["Play uncontested for one team to work a weakness"],
    regressions: ["Shorter halves", "Fewer players and a smaller pitch"],
    safety:
      "Full age grade rules including every contact restriction for the grade. Referee the tackle height and the ruck properly. If a child is tired enough to be tackling badly, take them off.",
  },
];
