import type { Drill } from "../types.js";

/** Passing, catching and looking after the ball. See docs/content-sourcing.md. */
export const HANDLING: Drill[] = [
  {
    id: "drill-two-hand-relay",
    title: "Two hand relay",
    kind: "exercise",
    themes: ["handling"],
    minAge: "u7",
    minutes: 8,
    players: { min: 6, max: 24 },
    space: "20 m channel",
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup: "Teams of four in lines. A turning cone ten metres out from each line.",
    howItRuns:
      "Run to the cone, round it, back, hand the ball over with two hands. Not a throw, a hand over. First team with everyone sat down wins. Three races. The only thing you are coaching is that the ball is carried in two hands and given properly, because at this age a one handed carry is where every dropped ball starts.",
    coachingPoints: [
      "Two hands on the ball. Both of them, all the way",
      "Hand it over, do not throw it",
      "Look at the person you are giving it to",
    ],
    progressions: ["Carry two balls", "Round the cone the other way so they turn both directions"],
    regressions: ["Shorter run", "Walk it once through first"],
  },
  {
    id: "drill-pass-down-the-line",
    title: "Pass down the line",
    kind: "exercise",
    themes: ["handling"],
    minAge: "u7",
    minutes: 8,
    players: { min: 6, max: 21 },
    space: "20 x 15 m",
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "Threes side by side, three metres apart, at one end of a channel.",
    howItRuns:
      "Walk forward together passing along the line. Reach the far cones, turn round, come back the other way. Six lengths. Then jog it. Keep the line flat, because the second one child runs ahead the pass has to go forward and it all falls apart. Point that out once, then let them feel it.",
    coachingPoints: [
      "Stay level with each other. Nobody races ahead",
      "Pass across your body with your fingers, not a swing of the arms",
      "Hands up and out before it comes to you",
    ],
    progressions: ["Jog it", "Fours instead of threes so the ball travels further"],
    regressions: ["Walk it", "Two metres apart instead of three"],
  },
  {
    id: "drill-corner-ball",
    title: "Corner ball",
    kind: "exercise",
    themes: ["handling", "gamesense"],
    minAge: "u7",
    minutes: 10,
    players: { min: 8, max: 20 },
    space: "20 x 20 m",
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup:
      "A square with a scoring box in each far corner. Two teams. Score by putting the ball down in either box.",
    howItRuns:
      "Touch rules with no contest at the touch. Hand it back, play on from there. Two scoring corners instead of one line means the defence has to spread out, so the attack starts looking for the empty one on its own. Four minute games, change the teams round.",
    coachingPoints: [
      "Before you get the ball, look at which corner has fewer defenders",
      "Straighten up and hold a defender before you pass",
      "Support either side of the carrier, do not follow behind them",
    ],
    progressions: ["One touch then the ball must move within three seconds", "A third scoring corner"],
    regressions: ["More attackers than defenders", "Bigger square"],
  },
  {
    id: "drill-catch-and-turn",
    title: "Catch and turn",
    kind: "exercise",
    themes: ["handling"],
    minAge: "u7",
    minutes: 7,
    players: { min: 6, max: 18 },
    space: "10 x 10 m",
    equipment: [{ item: "ball", qty: 1, per: "pair" }],
    setup: "Pairs, five metres apart, one ball each pair.",
    howItRuns:
      "Throw it up above their head so they have to reach. They catch, turn, put the ball on the floor behind them, pick it up, throw it back. Twenty each. Reaching for a high ball with both hands is a habit and this is how you build it without anybody feeling tested.",
    coachingPoints: [
      "Reach up for it. Do not wait for it to come down to your chest",
      "Fingers spread, thumbs together on a high one",
      "Watch it all the way in",
    ],
    progressions: ["Throw it slightly to one side so they have to move", "Catch it above your head"],
    regressions: ["Closer together", "Throw it chest high"],
  },
  {
    id: "drill-pop-pass-gates",
    title: "Pop pass gates",
    kind: "exercise",
    themes: ["handling"],
    minAge: "u8",
    minutes: 8,
    players: { min: 6, max: 18 },
    space: "20 x 10 m",
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup: "Four gates of two cones, two metres wide, spread up a channel. Pairs at the start.",
    howItRuns:
      "Run at each gate together. The carrier goes to one side of it, the support runs through it and takes a short pass off the hip. Four gates, then swap who carries. Six goes each. This is the pass they will actually use at a ruck in two years, so it is worth getting the timing early.",
    coachingPoints: [
      "Short and soft. A pop is not a spin pass",
      "Support runs onto it at pace, do not slow down for it",
      "Give it late. Too early and the defender reads it",
    ],
    progressions: ["Add a defender in one gate who can only stand still"],
    regressions: ["Wider gates", "Walk through the first two gates"],
  },
  {
    id: "drill-numbers-up",
    title: "Numbers up",
    kind: "exercise",
    themes: ["gamesense", "handling"],
    minAge: "u8",
    minutes: 12,
    players: { min: 9, max: 21 },
    space: "25 x 20 m",
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup:
      "Three attackers against two defenders across a channel. Everyone else waits behind the line and rotates in.",
    howItRuns:
      "One go to score. Score and they go again with the same numbers. Get stopped and the defence gets an extra player next go. Keep going until the defence is winning then reset to three against two. The attackers have to see the spare player and use them before the space shuts.",
    coachingPoints: [
      "Count the defence out loud before you start. Say the number",
      "Run at the inside shoulder to commit your defender",
      "Pass early enough that they still have space to run into",
    ],
    progressions: ["Four against three in a wider channel", "Defence starts a metre closer"],
    regressions: ["Three against one", "Defenders may only move sideways"],
  },
  {
    id: "drill-loop-and-go",
    title: "Loop and go",
    kind: "exercise",
    themes: ["handling"],
    minAge: "u8",
    minutes: 9,
    players: { min: 6, max: 18 },
    space: "20 x 15 m",
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "Pairs at one end of a channel, one defender halfway up who can walk forwards only.",
    howItRuns:
      "Carrier passes, then runs round behind the receiver to take it straight back. Two passes, one defender beaten. Six goes each way. The first time it works properly they will look genuinely pleased with themselves, which is the best reason to do it.",
    coachingPoints: [
      "Pass then move. Do not stand and admire it",
      "Go round behind them, close enough to take it back easily",
      "Receiver holds the defender for a beat before giving it back",
    ],
    progressions: ["Two defenders", "The loop has to happen at pace with no slowing down"],
    regressions: ["No defender at all to start", "Walk the pattern first"],
  },
  {
    id: "drill-switch-pass",
    title: "Switch",
    kind: "exercise",
    themes: ["handling", "evasion"],
    minAge: "u9",
    minutes: 9,
    players: { min: 6, max: 18 },
    space: "20 x 15 m",
    equipment: [{ item: "cone", qty: 6 }, { item: "ball", qty: 1 }],
    setup: "Pairs running up a channel with one defender halfway who may walk forward only.",
    howItRuns:
      "The carrier runs one way. The support runner cuts back behind them the other way and the ball changes hands as they cross. Six goes each. It only works if the carrier takes the defender wide first, so if it keeps failing that is why.",
    coachingPoints: [
      "Carrier goes wide first to drag the defender across",
      "Support cuts behind, close enough to take it easily",
      "Hide the ball from the defender as it changes hands",
    ],
    progressions: ["Two defenders", "Threes so there is a dummy switch option"],
    regressions: ["No defender", "Walk the pattern through first"],
  },
  {
    id: "drill-under-pressure-hands",
    title: "Under pressure hands",
    kind: "exercise",
    themes: ["handling"],
    minAge: "u9",
    minutes: 10,
    players: { min: 8, max: 20 },
    space: "20 x 20 m",
    equipment: [{ item: "cone", qty: 4 }, { item: "ball", qty: 2 }],
    setup: "Two teams in a square. One team has both balls.",
    howItRuns:
      "Keep the ball for ten passes to score a point. Defenders can touch the carrier. A touch means the ball goes down for the other team to pick up. Two balls at once so nobody hides. Four minute games. Hands go to pieces under pressure, which is exactly why you practise them under pressure.",
    coachingPoints: [
      "Move after you pass. A stood still player is no use",
      "Pass before the touch, not as it lands",
      "Talk. Tell them where you are",
    ],
    progressions: ["Eight passes instead of ten so it is quicker", "Smaller square"],
    regressions: ["Five passes", "One ball", "Defenders start two steps back"],
  },
  {
    id: "drill-offload-in-the-tackle",
    title: "Offload in the tackle",
    kind: "exercise",
    themes: ["handling", "tackle"],
    minAge: "u10",
    minutes: 10,
    players: { min: 6, max: 18 },
    space: "15 x 15 m",
    equipment: [{ item: "ball", qty: 1, per: "pair" }, { item: "tackle shield", qty: 1, per: "pair" }],
    setup: "Threes. A shield holder, a carrier and a support runner three metres behind.",
    howItRuns:
      "The carrier walks into the shield, stays on their feet and pops the ball to the support runner arriving on their shoulder. Then jog it. Six each. They are learning to keep their hands free in contact rather than curling up round the ball the second they get held.",
    coachingPoints: [
      "Take the contact on the shoulder, keep the ball in two hands",
      "Support arrives late and loud so you know they are there",
      "Pop it before you go to ground, not after",
    ],
    progressions: ["Carrier gets held by two shields", "Support arrives from the other side"],
    regressions: ["Walk the whole thing", "Support stands still and calls for it"],
    safety:
      "Shield holders brace and absorb, never drive. Contact at hip height only. Nobody goes to ground in this one, so stop it if it turns into a wrestle.",
  },
  {
    id: "drill-square-and-pass",
    title: "Square and pass",
    kind: "exercise",
    themes: ["handling", "gamesense"],
    minAge: "u10",
    minutes: 10,
    players: { min: 8, max: 21 },
    space: "30 x 20 m",
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup: "A line of four attackers against three defenders standing on a marked line.",
    howItRuns:
      "Attackers start drifting sideways. On your call they have to square up, run straight and then move the ball. Defenders can only move forward once the ball moves. Six goes then swap over. Drifting across the pitch is the most common thing minis do wrong and this makes it obvious why.",
    coachingPoints: [
      "Straighten up before you pass. Running sideways gives the defence time",
      "Fix your defender by running at them",
      "Ball moves quicker than feet. Do not run it to the touchline",
    ],
    progressions: ["Defenders may move as soon as the attack does"],
    regressions: ["Five attackers against three", "Defenders walk"],
  },
  {
    id: "drill-blind-pass-drill",
    title: "Hands without looking",
    kind: "exercise",
    themes: ["handling"],
    minAge: "u10",
    minutes: 8,
    players: { min: 6, max: 18 },
    space: "20 x 10 m",
    equipment: [{ item: "cone", qty: 4 }, { item: "ball", qty: 1 }],
    setup: "Threes in a line jogging up a channel. You stand off to one side.",
    howItRuns:
      "As the line jogs, you hold up a number of fingers. The carrier has to shout the number before passing on. It forces their eyes up off the ball. Four lengths each. They will drop a few at first, which is the point being made for you.",
    coachingPoints: [
      "Eyes up. Feel the pass, do not watch it",
      "Catch with your fingers not your palms",
      "Say the number loud enough that everyone hears it",
    ],
    progressions: ["Hold the number up on the far side so they have to properly look across"],
    regressions: ["Walk it", "Call the number out loud yourself as well"],
  },
  {
    id: "drill-spin-pass-build",
    title: "Spin pass build",
    kind: "exercise",
    themes: ["handling"],
    minAge: "u11",
    minutes: 9,
    players: { min: 6, max: 20 },
    space: "15 x 15 m",
    equipment: [{ item: "ball", qty: 1, per: "pair" }],
    setup: "Pairs, kneeling, five metres apart.",
    howItRuns:
      "From the knees, spin passes to each other. Twenty each side. Knees take the legs out of it so all they can do is use their hands. Then stand up, go to eight metres and do twenty more. Then jog and pass. A long pass is a wrist and a follow through, not a big heave. Kneeling proves that faster than any explanation.",
    coachingPoints: [
      "Bottom hand pushes, top hand guides the spin",
      "Follow through towards the target with both hands",
      "Ball comes off the fingers, not the palm",
    ],
    progressions: ["Stretch to twelve metres", "Pass off both hands equally"],
    regressions: ["Stay kneeling and closer", "No spin at all, just a firm push pass"],
  },
  {
    id: "drill-two-on-one-continuous",
    title: "Two on one, no stopping",
    kind: "exercise",
    themes: ["handling", "gamesense"],
    minAge: "u11",
    minutes: 12,
    players: { min: 9, max: 21 },
    space: "40 x 20 m",
    equipment: [{ item: "cone", qty: 8 }, { item: "ball", qty: 1 }],
    setup:
      "Two attackers set off from one end. One defender comes out to meet them. Fresh defenders wait at each of four stations up the pitch.",
    howItRuns:
      "Beat the first defender, keep going, the next one comes out. Four in a row without stopping. Then jog to the back and the next pair go. Two goes each. Their decision making holds up fine when fresh and falls apart by the fourth defender, which is when a match actually gets decided.",
    coachingPoints: [
      "Fix the defender then pass. Do not pass early out of habit",
      "Support stays behind the ball and a bit wide",
      "Talk between yourselves. Silence means somebody guesses",
    ],
    progressions: ["Three attackers against two at each station", "Five stations"],
    regressions: ["Two stations", "Defenders may only move sideways"],
  },
  {
    id: "drill-scrum-half-clearing-pass",
    title: "Clearing pass off the floor",
    kind: "exercise",
    themes: ["handling"],
    minAge: "u11",
    minutes: 9,
    players: { min: 4, max: 16 },
    space: "20 x 15 m",
    equipment: [{ item: "cone", qty: 4 }, { item: "ball", qty: 2 }],
    setup: "A ball on the ground. A passer beside it, a receiver eight metres away.",
    howItRuns:
      "Pick the ball up off the floor and pass it in one movement. No standing up first. Ten each side, then swap. Every child in the squad does this, not just whoever fancies themselves at nine, because on a Sunday somebody else will be doing it.",
    coachingPoints: [
      "Get your feet to the ball before your hands",
      "Sweep it away in one movement, do not lift then pass",
      "Point your back foot at the target",
    ],
    progressions: ["Ball is rolled to them so they arrive at it moving", "Pass off both sides"],
    regressions: ["Shorter pass", "Two movements allowed to start with"],
  },
];
